### ISSUE TITLE
kvtracer issue

### ISSUE THREAD

**Issue by ZaidQureshi** [stormspirit/imembench#3]
When I try to run the following command in the kvtracer directory 
mvn -pl kvtracer -am clean package

I get the output shown here: http://pastebin.com/DuvV5vLe

My directory structure is:
ycsb-0.7.0/kvtracer

**Comment by ryanphuang** [comment]
You need to update the `pom.xml` file to include `kvtracer` module. See the updated README. Also, the `pom.xml` inside `kvtracer` is for an older version of YCSB. If you want to use it with newer version like 0.7.0, you need to change it slightly. See https://github.com/stormspirit/YCSB/blob/master/kvtracer/pom.xml.

**Comment by ZaidQureshi** [comment]
Alright so i pulled the latest YCSB-0.9.0, fixed the version with the pom.xml from kvtracer. but now when I try to run mvn -pl kvtracer -am clean package, i get the following output http://pastebin.com/F0iG5ST0

When I try to compile everything in the YCSB directory everything passes except for kvtracer which fails. I am sorry the output I posted is too long but I can't decipher it.

**Comment by ryanphuang** [comment]
You need to disable checkstyle to pass compilation. `mvn -Dcheckstyle.skip=true -pl kvtracer -am clean package`.

If you are using YCSB 0.9.0, the DB interfaces are slightly changed. You should use the `kvtracer` in https://github.com/stormspirit/YCSB/tree/master/kvtracer.
